In [36]:
from selenium.webdriver import Chrome, Firefox
from functions import scrape_pages

In [37]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [18]:
browser = Firefox()
scrape_pages(1, browser)

[]

In [79]:
browser = Firefox()
url = 'https://www.coches.net/segunda-mano/'
browser.get(url)

In [ ]:
listings = browser.find_elements_by_class_name('mt-SerpList-item')

In [80]:
for listing in listings:

In [146]:
listings_info = []

for listing in listings:
        headline = listing.find_element_by_class_name('mt-CardAd-titleHiglight').text
        listing_id = listing.get_attribute("id") 
        
        #unpack attributes
        attributes = listing.find_elements_by_class_name('mt-CardAd-attribute')
        
        attr_list = []
        for attribute in attributes:
            attr_list.append(attribute.text)
            
        try:
            year = int(attr_list[2])
        except:
            pass
        
        try:
            location = attr_list[0]
        except:
            pass
        
        try:
            fuel_type = attr_list[1]
        except:
            pass
        
        #extract km integer from string
        try:
            km = attr_list[3]
            km = km.replace('.', '')
            km = int(km[:-3])
        except:
            pass
        
        price = []
        price_element = listing.find_elements_by_class_name('mt-AdPrice-amount')
        for element in price_element:
            price.append(element.text) 
        
        print(price[0])
        
        #for char in price:
            #if int(char):
                  #price_int.append(char) 
        
        
        #listing_url = 
        #km = 

        listings_info.append({
            'id': listing_id,
            'headline': headline,
            'attributes': attr_list,
            'price': price,
            'year': year,
            'location': location,
            'fuel_type': fuel_type,
            'km': km
        })

Precio al contado
8.750 €
Precio al contado
23.400 €
Precio al contado
11.990 €
Precio al contado
7.990 €
Precio al contado
20.550 €
Precio al contado
20.500 €
Precio al contado
12.990 €
Precio al contado
6.990 €

IndexError: list index out of range

In [144]:
len(listings_info)

31

In [145]:
listings_info

[{'id': '#40967681',
  'headline': 'BMW X3 3.0i 5p.',
  'attributes': ['Barcelona', 'Gasolina', '2005', '103.000 km'],
  'price': ['Precio al contado\n8.750 €'],
  'year': 2005,
  'location': 'Barcelona',
  'fuel_type': 'Gasolina',
  'km': 103000},
 {'id': '#40967680',
  'headline': 'OPEL Grandland X 1.5 CDTi 120 Aniversario 5p.',
  'attributes': ['Teruel', 'Diésel', '2019', 'N/D km'],
  'price': ['Precio al contado\n23.400 €', 'Precio financiado\n21.400 €'],
  'year': 2019,
  'location': 'Teruel',
  'fuel_type': 'Diésel',
  'km': 'N/D km'},
 {'id': '#40967679',
  'headline': 'OPEL Insignia 2.0 CDTI ecoFLEX SS 163 CV Excellence 5p.',
  'attributes': ['Zaragoza', 'Diésel', '2014', '156.000 km'],
  'price': ['Precio al contado\n11.990 €', 'Precio financiado\n10.990 €'],
  'year': 2014,
  'location': 'Zaragoza',
  'fuel_type': 'Diésel',
  'km': 156000},
 {'id': '#40967678',
  'headline': 'BMW Serie 5 530I 4p.',
  'attributes': ['Zaragoza', 'Gasolina', '2007', '181.000 km'],
  'price': ['Precio al contado\n7.990 €', 'Precio financiado\n7.990 €'],
  'year': 2007,
  'location': 'Zaragoza',
  'fuel_type': 'Gasolina',
  'km': 181000},
 {'id': '#40967669',
  'headline': 'NISSAN XTRAIL dCi 130CV 96kW XTRONIC TEKNA 7 plazas 5p.',
  'attributes': ['Madrid', 'Diésel', '2015', '76.000 km'],
  'price': ['Precio al contado\n20.550 €'],
  'year': 2015,
  'location': 'Madrid',
  'fuel_type': 'Diésel',
  'km': 76000},
 {'id': '#40967668',
  'headline': 'NISSAN QASHQAI DIGT 85 kW 115 CV NCONNECTA 5p.',
  'attributes': ['Madrid', 'Gasolina', '2018', '37.500 km'],
  'price': ['Precio al contado\n20.500 €', 'Precio financiado\n19.500 €'],
  'year': 2018,
  'location': 'Madrid',
  'fuel_type': 'Gasolina',
  'km': 37500},
 {'id': '#40967664',
  'headline': 'MINI MINI One Cabrio 2p.',
  'attributes': ['Zaragoza', 'Gasolina', '2010', '40.000 km'],
  'price': ['Precio al contado\n12.990 €', 'Precio financiado\n11.990 €'],
  'year': 2010,
  'location': 'Zaragoza',
  'fuel_type': 'Gasolina',
  'km': 40000},
 {'id': '#40967659',
  'headline': 'MERCEDES-BENZ Clase A A 180 CDI ELEGANCE 5p.',
  'attributes': ['Zaragoza', 'Diésel', '2008', '139.990 km'],
  'price': ['Precio al contado\n6.990 €', 'Precio financiado\n6.990 €'],
  'year': 2008,
  'location': 'Zaragoza',
  'fuel_type': 'Diésel',
  'km': 139990},
 {'id': 'PubNativeAds',
  'headline': 'Ofertas en Km0 y Nuevo en Stock',
  'attributes': ['Descubre más de 24.000 ofertas de coches de las mejores marcas y modelos'],
  'price': [],
  'year': 2008,
  'location': 'Descubre más de 24.000 ofertas de coches de las mejores marcas y modelos',
  'fuel_type': 'Diésel',
  'km': 139990},
 {'id': '#40967658',
  'headline': 'BMW X4 xDrive20d 5p.',
  'attributes': ['Valencia', 'Diésel', '2015', '78.000 km'],
  'price': ['Precio al contado\n28.900 €', 'Precio financiado\n26.900 €'],
  'year': 2015,
  'location': 'Valencia',
  'fuel_type': 'Diésel',
  'km': 78000},
 {'id': '#40967653',
  'headline': 'OPEL Corsa 1.3 CDTi StartStop Selective 95 CV 5p.',
  'attributes': ['Madrid', 'Diésel', '2015', '39.000 km'],
  'price': ['Precio al contado\n8.300 €'],
  'year': 2015,
  'location': 'Madrid',
  'fuel_type': 'Diésel',
  'km': 39000},
 {'id': '#40967652',
  'headline': 'VOLKSWAGEN Golf Sport 2.0 TDI 150cv BMT 5p.',
  'attributes': ['Madrid', 'Diésel', '2015', '61.000 km'],
  'price': ['Precio al contado\n15.600 €'],
  'year': 2015,
  'location': 'Madrid',
  'fuel_type': 'Diésel',
  'km': 61000},
 {'id': '#40967649',
  'headline': 'KIA Stonic 1.0 TGDi 74kW 100CV Concept 5p.',
  'attributes': ['Ávila', 'Gasolina', '2018', 'N/D km'],
  'price': ['Precio al contado\n16.990 €', 'Precio financiado\n14.490 €'],
  'year': 2018,
  'location': 'Ávila',
  'fuel_type': 'Gasolina',
  'km': 'N/D km'},
 {'id': '#40967648',
  'headline': 'BMW Serie 3 318CI 2p.',
  'attributes': ['Madrid', 'Gasolina', '2004', '150.000 km'],
  'price': ['Precio al contado\n4.000 €'],
  'year': 2004,
  'location': 'Madrid',
  'fuel_type': 'Gasolina',
  'km': 150000},
 {'id': '#40967647',
  'headline': 'SEAT Ibiza 1.2 TDI 75cv Reference 5p.',
  'attributes': ['Madrid', 'Diésel', '2015', '95.000 km'],
  'price': ['Precio al contado\n6.800 €'],
  'year': 2015,
  'location': 'Madrid',
  'fuel_type': 'Diésel',
  'km': 95000},
 {'id': '#40967646',
  'headline': 'RENAULT Clio Business Energy dCi 75 eco2 Euro 6 5p.',
  'attributes': ['Madrid', 'Diésel', '2016', '171.000 km'],
  'price': ['Precio al contado\n5.750 €'],
  'year': 2016,
  'location': 'Madrid',
  'fuel_type': 'Diésel',
  'km': 171000},
 {'id': '#40967643',
  'headline': 'FORD Ranger 3.2 TDCi 147kW 4x4 Dob Cab Wildtrack AT 4p.',
  'attributes': ['Zaragoza', 'Diésel', '2018', '14.259 km'],
  'price': ['Precio al contado\n33.500 €', 'Precio financiado\n31.990 €'],
  'year': 2018,
  'location': 'Zaragoza',
  'fuel_type': 'Diésel',
  'km': 14259},
 {'id': '#40967642',
  'headline': 'BMW Serie 3 320D TOURING 5p.',
  'attributes': ['Sevilla', 'Diésel', '2000', '217.000 km'],
  'price': ['Precio al contado\n2.500 €'],
  'year': 2000,
  'location': 'Sevilla',
  'fuel_type': 'Diésel',
  'km': 217000},
 {'id': '#40967641',
  'headline': 'AUDI A4 1.8 T multitronic 4p.',
  'attributes': ['Lleida', 'Gasolina', '2005', '170.000 km'],
  'price': ['Precio al contado\n2.990 €'],
  'year': 2005,
  'location': 'Lleida',
  'fuel_type': 'Gasolina',
  'km': 170000},
 {'id': '#40967640',
  'headline': 'VOLKSWAGEN Tiguan 2.0 TDI 140cv 4x2 Advance BMotion Tech 5p.',
  'attributes': ['Zaragoza', 'Diésel', '2012', '156.500 km'],
  'price': ['Precio al contado\n15.990 €', 'Precio financiado\n14.990 €'],
  'year': 2012,
  'location': 'Zaragoza',
  'fuel_type': 'Diésel',
  'km': 156500},
 {'id': '#40967635',
  'headline': 'NISSAN XTRAIL 1.6 DIGT TEKNA 5p.',
  'attributes': ['Zaragoza', 'Gasolina', '2017', '27.500 km'],
  'price': ['Precio al contado\n27.990 €', 'Precio financiado\n25.990 €'],
  'year': 2017,
  'location': 'Zaragoza',
  'fuel_type': 'Gasolina',
  'km': 27500},
 {'id': '#40967630',
  'headline': 'CHEVROLET Aveo 1.4 LTZ 5p.',
  'attributes': ['Zaragoza', 'Gasolina', '2013', '83.600 km'],
  'price': ['Precio al contado\n7.990 €', 'Precio financiado\n6.990 €'],
  'year': 2013,
  'location': 'Zaragoza',
  'fuel_type': 'Gasolina',
  'km': 83600},
 {'id': '#40967624',
  'headline': 'BMW Serie 5 520D 4p.',
  'attributes': ['Zaragoza', 'Diésel', '2015', '129.000 km'],
  'price': ['Precio al contado\n19.990 €', 'Precio financiado\n18.990 €'],
  'year': 2015,
  'location': 'Zaragoza',
  'fuel_type': 'Diésel',
  'km': 129000},
 {'id': '#39564934',
  'headline': 'AUDI SQ5 3.0 TDI 313cv quattro tiptronic 5p.',
  'attributes': ['Valencia', 'Diésel', '2015', '88.615 km'],
  'price': ['Precio al contado\n34.900 €'],
  'year': 2015,
  'location': 'Valencia',
  'fuel_type': 'Diésel',
  'km': 88615},
 {'id': '#35845527',
  'headline': 'AUDI Q3 2.0 TDI Advanced edition 5p.',
  'attributes': ['Badajoz', 'Diésel', '2014', '98.000 km'],
  'price': ['Precio al contado\n20.500 €', 'Precio financiado\n17.900 €'],
  'year': 2014,
  'location': 'Badajoz',
  'fuel_type': 'Diésel',
  'km': 98000},
 {'id': '#39535938',
  'headline': 'VOLKSWAGEN Polo Advance 1.6 TDI 70kW 95CV 5p.',
  'attributes': ['Alicante', 'Diésel', '2019', '100 km'],
  'price': ['Precio al contado\n16.300 €', 'Precio financiado\n14.300 €'],
  'year': 2019,
  'location': 'Alicante',
  'fuel_type': 'Diésel',
  'km': 100},
 {'id': '#39536600',
  'headline': 'VOLKSWAGEN Tiguan Edition 1.4 TSI 92kW 125CV 5p.',
  'attributes': ['Alicante', 'Gasolina', '2018', '11.822 km'],
  'price': ['Precio al contado\n23.300 €', 'Precio financiado\n21.300 €'],
  'year': 2018,
  'location': 'Alicante',
  'fuel_type': 'Gasolina',
  'km': 11822},
 {'id': '#39714249',
  'headline': 'BMW X1 sDrive18d 5p.',
  'attributes': ['Burgos', 'Diésel', '2019', '1 km'],
  'price': ['Precio al contado\n33.900 €', 'Precio financiado\n31.900 €'],
  'year': 2019,
  'location': 'Burgos',
  'fuel_type': 'Diésel',
  'km': 1},
 {'id': '#40082612',
  'headline': 'BMW Serie 5 520dA xDrive 4p.',
  'attributes': ['Barcelona', 'Diésel', '2014', '31.457 km'],
  'price': ['Precio al contado\n27.900 €', 'Precio financiado\n25.900 €'],
  'year': 2014,
  'location': 'Barcelona',
  'fuel_type': 'Diésel',
  'km': 31457},
 {'id': '#40274736',
  'headline': 'MERCEDES-BENZ Clase C C 200 d 4p.',
  'attributes': ['Murcia', 'Diésel', '2018', '19.468 km'],
  'price': ['Precio al contado\n36.500 €', 'Precio financiado\n36.500 €'],
  'year': 2018,
  'location': 'Murcia',
  'fuel_type': 'Diésel',
  'km': 19468},
 {'id': '#40906139',
  'headline': 'MERCEDES-BENZ Clase E E 220 BlueTEC 4p.',
  'attributes': ['Murcia', 'Diésel', '2017', '31.652 km'],
  'price': ['Precio al contado\n39.500 €', 'Precio financiado\n39.500 €'],
  'year': 2017,
  'location': 'Murcia',
  'fuel_type': 'Diésel',
  'km': 31652}]